### ISSUE TITLE
Problems with some centroids

### ISSUE THREAD

**Issue by SalmaSabour** [gavinr/world-countries-centroids#5]
Hi Gavin, 
Thank you for providing the data, it is really helpful.

Some of the centroids (such as US-US) are not situated in the middle of the land but on the ocean which could cause problems for visualization.

Thanks again,
Kindly,
Salma

**Comment by gavinr** [comment]
Hi, thank you for the feedback. The reason these are at odd locations is because they are the true centroid. And for cases like the USA, Alaska pulls the point northwest.

I intend to resolve this issue by changing the points to be the centroid of _the largest landmass_ under issue #3.
